name: Edunews

on:
  schedule:
    - cron: "15 15 * * *"   # Runs daily at 8:00 AM India time (2:30 AM UTC)
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Daily Digest
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        run: python daily_digest.py
